CREATE TABLE product (id SERIAL PRIMARY KEY, name VARCHAR(255), sale_units INT, stock_small INT, stock_medium INT, stock_large INT);

INSERT INTO product VALUES (1,'V-NECH BASIC SHIRT',100,4,9,0);
INSERT INTO product VALUES (2,'CONTRASTING FABRIC T-SHIRT',50,35,9,9);
INSERT INTO product VALUES (3,'RAISED PRINT T-SHIRT',80,20,2,20);
INSERT INTO product VALUES (4,'PLEATED T-SHIRT',3,25,30,10);
INSERT INTO product VALUES (5,'CONTRASTING LACE T-SHIRT',650,0,1,0);
INSERT INTO product VALUES (6,'V-NECH BASIC SHIRT',20,9,2,5);
